add pdx support

diff --git a/lib/start b/lib/start
--- a/lib/start
+++ b/lib/start
@@ -8,15 +8,22 @@ cd "$(dirname "$0")" && cd $(pwd)/..
 # environment
 . variables
 
-# require $NAME and $RUN
-[ -z "$NAME" ] && echo '$NAME is not defined' >&2 && exit 1
+# require $RUN & $NAME & $VERSION
 [ -z "$RUN" ] && echo '$RUN is not defined' >&2 && exit 1
+[ -z "$NAME" ] && echo '$NAME is not defined' >&2 && exit 1
+[ -z "$VERSION" ] && echo '$VERSION is not defined' >&2 && exit 1
+
+# versioned name
+FULL_NAME="$NAME@$VERSION"
 
 # bail if running
-ctrls/status > /dev/null && echo "$NAME is already running" >&2 && exit 1
+ctrls/status > /dev/null && echo "$FULL_NAME is already running" >&2 && exit 1
 
 # log date
-echo -e "\n"$(date)" starting up..." >> log
+echo -e "\n"$(date)" starting..." >> log
+
+# pdx
+export PORT=$(node_modules/.bin/pdx register $NAME)
 
 # start the service
 mon -d -p pid -m mpid -l log "$RUN"
@@ -25,4 +32,4 @@ mon -d -p pid -m mpid -l log "$RUN"
 sleep 0.5
 
 # are we up?
-ctrls/status > /dev/null && echo "$NAME started successfully" || (echo "$NAME failed to start" >&2 && exit 1)
+ctrls/status > /dev/null && echo "$FULL_NAME started successfully" || (echo "$FULL_NAME failed to start" >&2 && exit 1)
